config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'monsters#index'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  resources :monsters
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :monster, optional: false

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
  self.inheritance_column = :_type

  belongs_to :user, optional: true
  alias_attribute :author, :user
  has_many :traits
  has_many :actions
  has_many :reactions

  default_scope -> { order(name: :asc) }
  mount_uploader :picture, PictureUploader
  validates :name, presence: true, length: { maximum: 255 }
  validates :strength, :dexterity, :constitution, :intelligence, :wisdom, 
    :charisma, numericality: { only_integer: true, allow_nil: true }
  validate  :picture_size

  accepts_nested_attributes_for :traits, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :actions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reactions, reject_if: :all_blank, allow_destroy: true
  validates_associated :traits
  validates_associated :actions
  validates_associated :reactions

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :monster, optional: false

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :monster, optional: false

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/trait.rb
class Trait < ApplicationRecord
  belongs_to :monster, optional: false

  validates :name, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :monsters

  validates :username, presence: true, length: { maximum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :authorize_user, only: [:update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    flash.now[:alert] = t('.not_signed_in') unless user_signed_in?

    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)
    @monster.author = current_user
    if @monster.save
      redirect_to monster_path(@monster), notice: "Monster created!"
    else
      render 'new'
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: "Monster was successfully updated." }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    if @monster.destroy
      redirect_to monsters_path, notice: "Monster deleted."
    else
      redirect_to @monster, notice: "Failed to delete monster."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    def authorize_user
      if current_user != @monster.author
        redirect_to(@monster, notice: "You are not the author of this monster")
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).tap { |whitelisted| 
        whitelisted[:traits_attributes] = whitelisted[:traits] if whitelisted.has_key?(:traits) 
        whitelisted[:actions_attributes] = whitelisted[:actions] if whitelisted.has_key?(:actions)
        whitelisted[:reactions_attributes] = whitelisted[:reactions] if whitelisted.has_key?(:reactions)
      }.except(:traits).except(:actions).except(:reactions)
        .permit(:id, :name, :size, :type, :alignment, :armorClass, 
        :armorSource, :hitPoints, :hitDice, :speed, :strength, :dexterity, 
        :constitution, :intelligence, :wisdom, :charisma, :savingThrows, 
        :skills, :damageVulnerabilities, :damageResistances, :damageImmunities, 
        :conditionImmunities, :senses, :languages, :challenge,
        traits_attributes: [:id, :name, :description, :_destroy],
        actions_attributes: [:id, :name, :description, :_destroy],
        reactions_attributes: [:id, :name, :description, :_destroy])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Monster Maker"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/actions/_action.html.haml
.property-block
  %h4= "#{action.name}."
  = action.description

app/views/layouts/_footer.html.haml
%footer.footer
  %small Monster Maker by Raphaël Claasen
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li= link_to "News",    '#'

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-expand-md.navbar-dark.bg-dark
    .container
      = link_to "MonsterMaker", root_path, id: 'logo', class: 'navbar-brand'
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li.nav-item= link_to "Home", root_path, class: 'nav-link'
          %li.nav-item= link_to "Help", help_path, class: 'nav-link'
          - if user_signed_in?
            %li.nav-item= link_to "Edit Profile", edit_user_registration_path, class: 'nav-link'
            %li.nav-item= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link'
          - else
            %li.nav-item= link_to "Sign in", new_user_session_path, class: 'nav-link'
            %li.nav-item= link_to "Sign up", new_user_registration_path, class: 'nav-link'

app/views/layouts/_rails_default.html.haml
= csrf_meta_tags
= javascript_pack_tag    'application', 'data-turbolinks-track': 'reload'
= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>

app/views/layouts/_tags.html.haml
= csrf_meta_tags
= javascript_pack_tag    'application', 'data-turbolinks-track': 'reload'
= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = render 'layouts/tags'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/monsters/_action_fields.html.haml
.nested-fields
  = f.input :name
  = f.input :description
  = link_to_remove_association "Remove action", f

app/views/monsters/_form.html.haml
= simple_form_for @monster do |f|
  = f.input :name
  = f.input :picture, accept: 'image/jpeg,image/gif,image/png'
  = f.input :size
  = f.input :type
  = f.input :alignment
  = f.input :armorClass
  = f.input :armorSource
  = f.input :hitPoints
  = f.input :hitDice
  = f.input :speed
  = f.input :strength
  = f.input :dexterity
  = f.input :constitution
  = f.input :intelligence
  = f.input :wisdom
  = f.input :charisma
  = f.input :savingThrows
  = f.input :skills
  = f.input :damageVulnerabilities
  = f.input :damageResistances
  = f.input :damageImmunities
  = f.input :conditionImmunities
  = f.input :senses
  = f.input :languages
  = f.input :challenge
  %div
    %h3 Traits
    #traits
      = f.simple_fields_for :traits do |trait|
        = render 'trait_fields', f: trait
      .links
        = link_to_add_association "Add trait", f, :traits
  %div
    %h3 Actions
    #actions
      = f.simple_fields_for :actions do |action|
        = render 'action_fields', f: action
      .links
        = link_to_add_association "Add action", f, :actions
  %div
    %h3 Reactions
    #reactions
      = f.simple_fields_for :reactions do |reaction|
        = render 'reaction_fields', f: reaction
      .links
        = link_to_add_association "Add reaction", f, :reactions

  = f.button :submit, class: 'btn-primary'

app/views/monsters/_monster.html.haml
.stat-block
  .creature-heading
    %h1= @monster.name
    .subtitle= "#{@monster.size} #{@monster.type}, #{@monster.alignment}"

  = render "tapered_rule"

  .top-stats
    .property-line
      %h4 Armor Class
      = "#{@monster.armorClass} (#{@monster.armorSource})"
    .property-line
      %h4 Hit Points
      = "#{@monster.hitPoints} (#{@monster.hitDice})"
    .property-line
      %h4 Speed
      = @monster.speed

    = render "tapered_rule"

    %table.attributes-table
      %tr
        %th STR
        %th DEX
        %th CON
        %th INT
        %th WIS
        %th CHA
      %tr
        %td= @monster.strength
        %td= @monster.dexterity
        %td= @monster.constitution
        %td= @monster.intelligence
        %td= @monster.wisdom
        %td= @monster.charisma

    = render "tapered_rule"

    .property-line
      %h4 Saving Throws
      = @monster.savingThrows
    .property-line
      %h4 Skills
      = @monster.skills
    .property-line
      %h4 Damage Vulnerabilities
      = @monster.damageVulnerabilities
    .property-line
      %h4 Damage Resistances
      = @monster.damageResistances
    .property-line
      %h4 Damage Immunities
      = @monster.damageImmunities
    .property-line
      %h4 Condition Immunities
      = @monster.conditionImmunities
    .property-line
      %h4 Senses
      = @monster.senses
    .property-line
      %h4 Languages
      = @monster.languages
    .property-line
      %h4 Challenge
      = @monster.challenge
    
    = render "tapered_rule"

  = render @monster.traits

  %h3 Actions
  = render @monster.actions

  %h3 Reactions
  = render @monster.reactions
  

app/views/monsters/_property_fields.haml
.nested-fields
  = f.input :name
  = f.input :description
  = link_to_remove_association "Remove property", f

app/views/monsters/_reaction_fields.html.haml
.nested-fields
  = f.input :name
  = f.input :description
  = link_to_remove_association "Remove reaction", f

app/views/monsters/_tapered_rule.html.haml
%svg.tapered-rule{height: 5, width: 400}
  %polyline{points: "0,0 400,2.5 0,5"}

app/views/monsters/_trait_fields.haml
.nested-fields
  = f.input :name
  = f.input :description
  = link_to_remove_association "Remove trait", f

app/views/monsters/_trait_fields.html.haml
.nested-fields
  = f.input :name
  = f.input :description
  = link_to_remove_association "Remove trait", f

app/views/monsters/edit.html.haml
%h1 Editing Monster
= render 'form', monster: @monster
= link_to 'Back', @monster, class: "btn btn-outline-secondary"
|
= link_to 'Delete', @monster, method: :delete, data: { confirm: I18n.t("monsters.confirm_delete", monster_name: @monster.name) }, class: "btn btn-danger" 

app/views/monsters/index.html.haml
%h1 Monsters
%table.monster-list
  %thead
    %tr
      %th Name
      %th Type
      %th Challenge
      %th Author
  %tbody
    - @monsters.each do |monster|
      %tr
        %td= link_to monster.name, monster
        %td= monster.type
        %td= monster.challenge
        %td= monster.user&.username
%br/
= link_to 'Create Monster', new_monster_path, class: "btn btn-primary"

app/views/monsters/new.html.haml
- provide(:title, "Create a Monster")
%h1 Create a Monster
= render 'form', monster: @monster
= link_to 'Back', monsters_path

app/views/monsters/show.html.haml
- if @monster.author.present?
  .author By #{@monster.author.username}

= render 'monster'

= link_to "Back", monsters_path, class: 'btn btn-outline-secondary'
- if user_signed_in? && @monster.author == current_user
  |
  = link_to "Edit", edit_monster_path(@monster), class: 'btn btn-outline-primary'
  |
  = link_to "Delete", monster_path(@monster), method: :delete, data: { confirm: "This action cannot be reversed. Are you sure?" }, class: 'btn btn-outline-danger'

app/views/reactions/_reaction.html.haml
.property-block
  %h4= "#{reaction.name}."
  = reaction.description

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/about.html.haml
- provide(:title, "About")
%h1 About
%p
  Monster Maker is made by Raphaël Claasen and is available under the
  = succeed "." do
    %a{:href => "https://www.gnu.org/licenses/gpl.html"} GNU General Public License

app/views/static_pages/contact.html.haml
- provide(:title, "Contact")
%h1 Contact
%p Because I'm not that great at hiding my e-mail from the internet, you'll have to google me to find me.

app/views/static_pages/help.html.haml
- provide(:title, "Help")
%h1 Help
%p Get help by contacting me.

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Welcome to MonsterMaker
  %h2 This is the home page for the MonsterMaker application.
  = link_to "Create a monster!", new_monster_path, class: "btn btn-lg btn-primary"

app/views/traits/_trait.html.haml
.property-block
  %h4= "#{trait.name}."
  = trait.description